name: Core C CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    name: "💦 ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: setup (macos)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install cmake

    - name: setup (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y --no-install-recommends build-essential cmake valgrind time curl

    - name: build
      run: |
        mkdir build
        cd build
        cmake -D BUILD_LIQUID=ON -D BUILD_PYTHON=OFF ..
        make -j2
        ctest

